### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by FrozoYT** [Qays12/AutoMudaeRoller#1]
Could you Dm me of discord and assist me with the setup? My discord is .Frozo. Thank you very much.

**Comment by Qays12** [comment]
If you are unfamiliar with using the terminal to execute code, I created an exe file for that purpose. If you navigate to the code tab, on the right side of the screen, you should see releases. Click on it and download the exe file. If you need any help, ask, and I'll happily DM you on Discord. Hope this helps.

**Comment by FrozoYT** [comment]
Yes I Might need more help I can not find the exe file

**Comment by FrozoYT** [comment]
Alright, I ended up finding it and downloading it. But the only problem now is it executes my command too fast and only around 5 actually work. Thank you for your previous help.

**Comment by Qays12** [comment]
Thank you for that, I now gave you the option to input how many seconds you want for each roll to run for. This way it won't spam out like crazy. The default was 1 second. You are able to change it how you like. I updated the exe, check the latest release and download V3
